version: "3"

services:
  ckan-dev:
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    network_mode: "host"
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions:Z
      - ckan_storage:/var/lib/ckan

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"

  db:
    container_name: db
    network_mode: "host"
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    network_mode: "host"
    build:
      context: solr/

  redis:
    container_name: redis
    network_mode: "host"
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
