version: "3"

services:

  ckan:
    container_name: ckan
    deploy:
      labels:
        nz.co.pfr.description: "Plant and Food Research Data Conservatory"
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
      depends_on:
      - db
      - solr
      - redis
    env_file: .env-prod
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - /store/ckan:/var/lib/ckan:Z

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"

  db:
    container_name: db
    build:
      context: postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /store/pg:/var/lib/postgresql/data:Z

  solr:
    container_name: solr
    build:
      context: solr/
    volumes:
      - /store/solr:/opt/solr/server/solr/ckan/data/index:Z

  redis:
    container_name: redis
    image: redis:alpine


