SELECT [dim_sap_mc_wbs_element_key]
      ,[wbs_element_code]
      ,[wbs_element_name]
      ,[cofunding_type_key]
      ,[cofunding_type_name]
      ,[contract_number_key]
      ,[cofunding_contract_key]
      ,[system_status_key]
      ,[system_status_name]
      ,[user_status_key]
      ,[user_status_name]
      ,[start_date]
      ,[end_date]
      ,[dss_start_date]
      ,[dss_end_date]
      ,[dss_current_flag]
      ,[dss_version]
      ,[dss_update_time]
  FROM [dwtest].[dbo].[dim_sap_mc_wbs_element]
 
 